MEPH.define('Connection.constant.Constants', {
    statics: {
        LoggedIn: 'cONNECTION+LoggedIn',
        LoggedOut: 'connection_loggedout',
        ConnectionLogIn: 'Connection + log in',
        ConnectionLogOut: 'Connection log out',
        CurrentCard: 'Current card',
        CurrentContact: 'Current contact',
        ConnectionLost: 'Connection has been lost',
        MultipleLogins: 'Multiple logins from different providers',
        SECONDARY_MENU: 'SECONDARY_MENU',
        FAILED_TO_GET_TOKEN_REFRESH: 'Failed to get the token refresh from server',
        CurrentConversation: 'CurrentConversation',
        CurrentConversationContact: 'CurrentConversationContact',
        CurrentConversationContacts: 'CurrentConversationContacts',
        RefreshedToken: 'RefreshedToken',
        CurrentSelectionConfig: 'CurrentSelectionConfig',
        MergeSituation: 'MergeSituation',
        UnseenMessages: 'UnseenMessages',
        UseCamera: 'Use Camera',
        UsePictureFiles: 'Use Picture files',
        TakePicture: 'TakePicture',
        SavePicture: 'SavePicture',
        SelectProfileContactImageData: 'SelectProfileContactImageData',
        ContactProfileImagePath: 'contactProfileImagePath',
        ContactProfileImageProtocol: 'contactProfileImageProtocol',
        BridgeSource: 'bridge-source',
        TakeContactPicture: 'take contact image picture'
    }
})